### ISSUE TITLE
key=value not supported for ConfigMap - JSon is expected

### ISSUE THREAD

**Issue by cmoulliard** [cescoffier/vertx-configuration-service#4]
If a ConfigMap contains key=value pairs, then we get a Json exception

````
oc create configmap game-config --from-file=src/main/resources/ui.properties

File ui.properties =>

color.good=purple
color.bad=yellow
allow.textmode=true
how.nice.to.look=fairlyNice
````

Error

```
Sep 13, 2016 5:02:36 PM io.vertx.ext.configuration.impl.ConfigurationServiceImpl
SEVERE: Error while scanning configuration
io.vertx.core.json.DecodeException: Failed to decode:Unrecognized token 'color': was expecting ('true', 'false' or 'null')
 at [Source: color.good=purple
color.bad=yellow
allow.textmode=true
how.nice.to.look=fairlyNice; line: 1, column: 6]
        at io.vertx.core.json.Json.decodeValue(Json.java:82)
        at io.vertx.core.json.JsonObject.fromJson(JsonObject.java:850)
        at io.vertx.core.json.JsonObject.<init>(JsonObject.java:53)
        at io.vertx.core.buffer.impl.BufferImpl.toJsonObject(BufferImpl.java:82)
        at io.vertx.ext.configuration.impl.spi.JsonProcessor.process(JsonProcessor.java:21)
        at io.vertx.ext.configuration.impl.ConfigurationProvider.lambda$get$1(ConfigurationProvider.java:39)
        at io.vertx.ext.configuration.kubernetes.ConfigMapStore.lambda$get$3(ConfigMapStore.java:115)
        at io.vertx.core.impl.FutureImpl.checkCallHandler(FutureImpl.java:158)
        at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:100)
        at io.vertx.ext.configuration.kubernetes.ConfigMapStore.get(ConfigMapStore.java:111)
        at io.vertx.ext.configuration.impl.ConfigurationProvider.get(ConfigurationProvider.java:35)
        at io.vertx.ext.configuration.impl.ConfigurationServiceImpl.lambda$compute$8(ConfigurationServiceImpl.java:145)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at io.vertx.ext.configuration.impl.ConfigurationServiceImpl.compute(ConfigurationServiceImpl.java:154)
        at io.vertx.ext.configuration.impl.ConfigurationServiceImpl.scan(ConfigurationServiceImpl.java:126)
        at io.vertx.ext.configuration.impl.ConfigurationServiceImpl.lambda$new$1(ConfigurationServiceImpl.java:78)
        at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:782)
        at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:753)
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:316)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:440)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by cescoffier** [comment]
Did you set "format": "properties" in the store configuration ?

**Comment by cmoulliard** [comment]
Yes. The format is defined here as properties - https://github.com/cmoulliard/use-cases/blob/master/vertx-kube-configmap/src/main/java/io/vertx/example/kubernetes/MyVerticle.java#L15

**Comment by cescoffier** [comment]
This gets the correct result:

```
private void setUpConfiguration() {
    ConfigurationStoreOptions appStore = new ConfigurationStoreOptions();
    appStore.setType("configmap")
        .setFormat("properties")
        .setConfig(new JsonObject()
            .put("namespace", "vertx-demo")
            .put("name", "app-config")
            .put("key", "app.properties"));

    conf = ConfigurationService.create(vertx, new ConfigurationServiceOptions()
        .addStore(appStore));
  }
```

**Comment by cescoffier** [comment]
Do you have a reproducer ?

**Comment by cmoulliard** [comment]
Not anymore

**Comment by cescoffier** [comment]
Perfect :-)

Please reopen if you find the issue.
